#define BUILD_COMMIT_ID "d3d4a7d-dirty"
#define PROJECT_VERSION "2.18.3"
#define PROJECT_VERSION_BUILD_NO "10"
#define PROJECT_VERSION_LONG PROJECT_VERSION "." PROJECT_VERSION_BUILD_NO " (" BUILD_COMMIT_ID ")"
