#define BUILD_COMMIT_ID "4db138d-dirty"
#define PROJECT_VERSION "2.1.2"
#define PROJECT_VERSION_BUILD_NO "1251"
#define PROJECT_VERSION_LONG PROJECT_VERSION "." PROJECT_VERSION_BUILD_NO " (" BUILD_COMMIT_ID ")"
