#define BUILD_COMMIT_ID "17.9.26"
#define PROJECT_VERSION "2.1.1"
#define PROJECT_VERSION_BUILD_NO "1245"
#define PROJECT_VERSION_LONG PROJECT_VERSION "." PROJECT_VERSION_BUILD_NO " (" BUILD_COMMIT_ID ")"
